cesium/seium.org

src/assets/css/challenges.css, src/assets/css/home.css, src/assets/css/intro.css, src/assets/css/navChallenge.css, src/components/sections/agendaPage/agenda.js, src/components/sections/challenges/challenges.js, src/components/sections/landing/intro/intro.js, src/components/utils/sectionDescription.js
=> Add mascot animation when mouse hover

src/assets/css/profile.css, src/components/carousels/speakerEvent.js, src/components/carousels/speakerProfile.js, src/components/carousels/speakers-carousel.js
=> Add speakers social media button behaviour

package.json, src/components/sections/footer.js, yarn.lock
=> Footer animation

src/assets/css/navbar.css
We should have a register button on the website. For now, I am putting it on the navbar because it's the simplest way to do it.
=> Keep join us on navbar on mobile

src/assets/css/activity.css, src/assets/css/home.css, src/components/carousels/activity.js, src/components/carousels/agenda/day23.js, src/components/carousels/agenda/day24.js, src/components/carousels/agenda/day26.js, src/components/sections/landing/intro/intro.js
=> Add changes to agenda

src/components/sections/agendaPage/agenda.js
On PR #19 it was introduced a duplication of title and agenda carousel. This fixes that.
=> Fix agenda duplication

src/components/carousels/carousel-agenda.js, src/components/carousels/speakers-carousel.js
This PR makes the carousel day slider (on Agenda and Speakers) stick on scroll
=> Sticky carousel slider

src/assets/css/moonstone.css, src/components/moonstone/User/UserInfo.js
| before | now |
| :---: | :---:|
| ![image](https://user-images.githubusercontent.com/19409687/108455806-d292d180-7266-11eb-8889-50dacbf8cada.png) | ![image](https://user-images.githubusercontent.com/19409687/108455740-ad9e5e80-7266-11eb-8d67-b5f97d8c825a.png) |
=> Fix section header color

src/App.js
This makes it so the user won't logout after leaving its profile
=> Add authentication permanence

package.json, src/assets/css/moonstone.css, src/components/moonstone/Button.js, src/components/moonstone/awards/FixedWheel.js, src/components/moonstone/spinningWheel.js, src/components/moonstone/wheel/WheelComponent.js, src/pages/Wheel.js, yarn.lock
The wheel assumes that if no prize the returned String will be "Nada". This should actually be changed for a better name like "Damn luck, maybe next time!"
=> Add 'Spin the Wheel'

src/assets/css/home.css, src/assets/css/navbar.css
=> Fix navbar

components/moonstone/Award/index.jsx, pages/awards.js
Heading in separate branch ```ro/badge-slug```
=> Changed awards fonts

components/moonstone/CheckpointTracker/index.jsx, components/moonstone/CodeInput/index.jsx, components/moonstone/Input/index.jsx, components/utils/Button/index.jsx, pages/profile.js
The Heading fonts are changed in another branch ```ro/badge-slug```
=> Changed profile page fonts

components/website/challenges/Challenges/Challenge/index.jsx, components/website/challenges/Challenges/index.jsx, components/website/challenges/List/index.jsx, components/website/utils/Footer/index.jsx, pages/challenges.js
Made challenges sticky, fixed broken links / link colors and changed the footer text
=> Fixed challenges page

components/website/team/Organization/Member/index.jsx, components/website/team/Organization/Team/index.jsx
Edited the way the data is passed to the component
=> Add conditional rendering to social links

components/moonstone/user/leaderboard/LeaderboardTable/index.jsx, components/moonstone/user/leaderboard/Table/index.jsx, components/website/utils/Schedule/Day/index.jsx, pages/leaderboard.js
The ```<Day/>``` component needs to be refactored. The color of the arrow can't be changed for now, as it is a ```.svg``` file that would need to be edited / added to the repo.
=> Added leaderboard page

components/website/home/Speakers/index.jsx, data/jury.json, data/mentors.json, data/speakers_selection.json, pages/hackathon.js
Make people info comming from .json files where it wasn't previously
doing it.
=> People info from json

components/utils/Button/index.jsx, components/website/challenges/Challenges/Challenge/index.jsx, components/website/hackathon/Hero/index.jsx, components/website/hackathon/Regulations/index.jsx, components/website/home/Hackathon/index.jsx, components/website/home/Hero/Pitch/index.jsx, components/website/home/Speakers/index.jsx, components/website/utils/Schedule/Day/Filters/index.jsx, pages/login.js, pages/profile.js, pages/signup.js
=> :art: Make buttons Pretty

components/website/utils/Footer/index.jsx, components/website/utils/Footer/style.module.css, components/website/utils/Schedule/Table/Block/index.jsx, components/website/utils/Schedule/Table/index.jsx, components/website/utils/Schedule/index.jsx, pages/schedule.js, styles/globals.css
Clicking events on home now links to /schedule
Added smooth scrolling to /schedule
Added background color transition to /schedule when an event is selected
=> Fixed home's schedule clicking

components/website/utils/Schedule/Day/Filters/index.jsx, components/website/utils/Schedule/Day/index.jsx, components/website/utils/Schedule/Table/Block/index.jsx, components/website/utils/Schedule/Table/Block/style.module.css, components/website/utils/Schedule/index.jsx, components/website/utils/Schedule/style.module.css, data/schedule.json, pages/schedule.js
Made schedule component fully responsive
Last thing missing is setting the correspondence between the filters and the activity types (see Schedule/Table/index.jsx line 13)
=> Responsive schedule

pages/404.js
Made animation go behind it, added the URL to the main page, and refactored the page.
=> Fixed button in 404 page

components/utils/Button/index.jsx, components/website/challenges/Challenges/Challenge/index.jsx, components/website/hackathon/Hero/index.jsx, components/website/hackathon/Regulations/index.jsx, components/website/home/Hackathon/index.jsx, components/website/home/Hero/Pitch/index.jsx, components/website/home/Speakers/index.jsx, components/website/utils/Schedule/Day/Filters/index.jsx, pages/forgot-password.js, pages/login.js, pages/password-recovery.js, pages/profile.js, pages/signup.js
Added two pages:
```forgot-password``` is the page the user clicks in order to request the email to reset the password
```password-recovery``` is the page the users receives a link to in the email
I wasn't sure what to say in the card, so suggestions are welcome.
=> Added pages to reset password

data/jury.json, data/mentors.json
Added Hackathon jury and mentors to be announced
=> Add Hackathon Members TBA

components/website/home/Speakers/index.jsx
=> Add speakers link

components/website/home/Hackathon/index.jsx
=> Fix hackathon section

components/website/utils/Navbar/index.jsx
Added eventbrite link, it will be available on 15th at 9pm
=> add eventbrite link

components/website/challenges/Hero/index.jsx, components/website/faqs/index.jsx, components/website/hackathon/Hero/index.jsx, components/website/home/Hero/Organization/index.jsx, components/website/home/Hero/index.jsx, components/website/schedule/Hero/index.jsx, components/website/speakers/Hero/index.jsx, components/website/team/Hero/index.jsx, components/website/utils/JoinUs/index.jsx, components/website/utils/Navbar/index.jsx, pages/challenges.js, pages/faq.js, pages/hackathon.js, pages/index.js, pages/schedule.js, pages/signup.js, pages/speakers.js, pages/team.js
=> Make Navbar Responsive

components/website/hackathon/Hero/ExpectList/index.jsx, components/website/hackathon/Hero/Organization/index.jsx, components/website/hackathon/Hero/index.jsx, components/website/hackathon/Regulations/index.jsx
=> Fix hackathon responsiveness

components/website/hackathon/Awards/index.jsx, components/website/hackathon/Hero/ExpectList/index.jsx, components/website/hackathon/Hero/Pitch/index.jsx, components/website/hackathon/Hero/index.jsx, components/website/hackathon/Regulations/index.jsx, pages/hackathon.js
Closes #210
- Added missing company
- Added the prizes
- Added link to the registration form 
- Changed duplicated text
=> fill hackathon information and links

components/website/schedule/Hero/Title/index.jsx, components/website/utils/UnderlineAnimation/index.jsx
=> Fix mascot animation sm

components/website/utils/Schedule/Table/Block/index.jsx, components/website/utils/Schedule/index.jsx
Removed anchor scroll in /schedule
=> Removed scroll from Schedule

components/website/hackathon/Hero/index.jsx, components/website/home/Hackathon/index.jsx
changed number of team members for hackathon
=> fixed hackathon numbers

pages/attendee/badgedex.js
=> Add badge filters

data/badge_types.json, pages/attendee/badgedex.js
=> Remove secret type from badge filters

components/website/utils/Navbar/index.jsx
=> Add user navigation for different types

data/schedule.json
=> Surname typpo

components/Auth/AuthProvider.js, components/moonstone/utils/QRScanner/BarebonesQRScanner/index.jsx, components/moonstone/utils/QRScanner/index.jsx, lib/api.js, pages/attendee/profile.js, pages/register/[uuid].js
We need a `/attendees/uuid` page that we can use to show the user profile, but also redirect to register if the attendee is not registered yet.
=> Add register page and improve signup function

components/Auth/withAuth.js, lib/api.js, pages/attendees/[uuid].js
This could be reviewed if https://github.com/cesium/safira/issues/274 is fixed.
=> Fix bugs and improve setup flow

components/website/hackathon/Hero/Title/index.jsx, components/website/schedule/Hero/Title/index.jsx
=> Fix title sizes

components/website/speakers/Schedule/index.jsx, components/website/utils/Schedule/index.jsx
Fixed date shown beyond the max date
=> Fixed date displayed on Schedule

context/Auth/AuthProvider.js, layout/Login/components/LoginForm/index.tsx
Added error decoding in login and edit user endpoints
=> Fix issue #406

components/website/challenges/Challenges/index.jsx
Before, the text was always being centered, resulting on it changing its position between different challenges days. Now its position is more concise.
=> Enhance challenges page

layout/Attendee/Profile/Profile.tsx, layout/Attendee/Profile/components/CVInput/index.tsx
Probably not the best branch to merge this to, but CV uploading is implemented here. Again there is no design for this, so I just made something up.
=> Add CV upload

context/Auth/AuthProvider.js, layout/Attendee/Profile/Profile.tsx, layout/Attendee/Profile/components/CVInput/index.tsx, lib/api.js
Add upload profile avatar photo feature.
This feat. does not includes Drag and Drop image upload, but it can be implemented, what do you guys think?
=> add(Attendee/Profile): Upload photo and CV

layout/Sponsor/Visitors/Visitors.tsx, layout/Sponsor/components/Pagination.jsx, lib/api.js
There are some problems still with this page. I plan on working on it further after this gets merged (mainly adding paging, fixing some responsiveness issues).
=> Allow company to download CV of attendees who visited it

components/Balance/index.jsx, components/Base/index.jsx, components/Dashboard/index.jsx, layout/Product/Product.tsx, layout/Product/components/Base.jsx, layout/Product/index.tsx, pages/product/[slug].tsx
Also refactor page to new filesystem
resolve #417
=> ref(pages/product): Change page and image background color

components/Button/index.tsx, generator/templates/components/component.tsx.hbs, layout/Attendees/index.ts, layout/Sponsor/Spotlight/Spotlight.tsx, package.json
=> Revert "Fix build"

components/JoinUs/index.jsx
As @laraujo7 suggested, I've changed the button to pure CSS instead of just an SVG that is not future proof.
=> Fix Join Us button

context/Auth/AuthProvider.js, layout/SignUp/components/SignUpForm/index.tsx
=> Added thorough vaildation front-end side

layout/SignUp/components/SignUpForm/index.tsx
This follows, strictly, all the constraints imposed by safira.
=> Fix signup validation

components/Layout/Layout.tsx, components/QRCodeCanvas/index.tsx, context/Auth/withAuth.js, layout/Attendee/Identifier/Identifier.tsx, layout/Attendee/Identifier/index.tsx, package-lock.json, package.json, pages/attendee/identifier.tsx
This page can be useful if the attendee forgot his credential
=> feat(pages/identifier): Page that generates qrcode to identify attendee

layout/Attendee/Vault/Vault.tsx
I haven't tested it yet because I don't have an attendee account. Would one of you kind souls mind testing? :)
=> Fixed that thing where some people can't see their prizes in the vault

layout/Home/components/Hero/Pitch/index.jsx
=> fix: hero pitch typo

layout/Attendee/Wheel/Wheel.tsx, layout/Attendee/Wheel/components/WheelComponent/index.tsx, lib/api.js, public/images/wheel-arrow.svg
=> feat: improve wheel

layout/Manager/Badges/Badges.tsx
=> Placeholder added in badges file

layout/FAQs/FAQs.tsx
=> fix: Remove "reprovaste a algoritmos" from FAQs

lib/api.js
Depends on [#348](https://github.com/cesium/safira/pull/348) from safira.
Removes version identifier from the API endpoints.
=> refactor: update api endpoints

layout/Attendee/Wheel/Wheel.tsx, lib/api.js
Wheel pricing was hardcoded, now it gets the price dynamically from the backend.
Depends on [#349](https://github.com/cesium/safira/pull/349) from safira.
Fixes #562
=> feat: fetch wheel price from api

layout/Attendee/Profile/Profile.tsx
=> feat: remove referral code section from profile page

layout/Challenges/components/Challenges/Challenge/index.tsx, layout/Challenges/components/Challenges/index.jsx
Fix #522 , also fixes the font (was using the old one)
=> feat: animate challenges page components

components/Button/index.tsx, components/Layout/Layout.tsx, layout/Attendee/Profile/Profile.tsx, layout/Attendee/Wheel/Wheel.tsx, layout/Challenges/components/Challenges/Challenge/index.tsx, layout/Home/components/Hero/Pitch/index.jsx, layout/Home/components/Speakers/index.jsx, layout/Login/components/LoginForm/index.tsx, layout/Product/Product.tsx, layout/ResetPassword/components/ResetPasswordForm/index.tsx, layout/SignUp/components/SignUpForm/index.tsx, layout/Staff/components/StaffRedeemButton/index.jsx, layout/moonstone/sponsor/dashboard/SponsorBadgeButton/index.jsx, layout/moonstone/sponsor/dashboard/SponsorPrizeButton/index.jsx, layout/moonstone/sponsor/spotlight/SpotlightButton/index.jsx, layout/shared/Leaderboard/Leaderboard.tsx, pages/register/[uuid].js
=> fix: standardize button component implementation

layout/Speakers/components/Schedule/index.jsx, layout/shared/Leaderboard/Leaderboard.tsx
Some dates were still hardcoded. Fix #514
=> chore: make all event dates fetch from schedule

components/Navbar/index.jsx, layout/Team/components/Organization/index.jsx
=> fix: SEI animation placement on team page

components/PasswordInput/index.tsx, styles/globals.css
Removes bad looking autofill background color that browsers add to login and signup forms, 
Replaces Favicons with HeroIcons on password input field
=> feat: improve authentication forms

layout/Challenges/components/Challenges/Challenge/index.tsx
Fixed the alignment issue of  place under the award section in the Challenges page.
Fixes #511
=> fix: alignment issue of place under the award section

lib/api.js
File uploads were not working in staging.
=> fix: file upload not working

data/schedule.json, data/speakers.json
=> chore: CodSec workshop

data/schedule.json
Only two pitches missing (TBD)
=> chore: add (mostly) all pitches

components/Badge/index.tsx, context/Auth/AuthContext.tsx, lib/api.js
Depends on [safira/#367](https://github.com/cesium/safira/pull/367).
=> refactor: simplify get current user logic

package-lock.json
`npm i` was showing 1 moderate security vulnerability. This PR fixes it.
=> fix: moderate security vulnerability

layout/Home/Home.tsx, layout/Home/components/Hero/ExpectList/index.jsx, layout/Home/components/Hero/index.tsx
=> fix: gradient z-index issues on hero component

layout/Attendees/Attendees.tsx
=> fix: attendee profile subtitle

data/schedule.json
=> feat: movie night

components/Footer/index.tsx, layout/FAQs/FAQs.tsx
Before we had any data on the website, void's message bubble was changed. This PR re-adds it.
=> chore: change footer message

layout/Attendee/Profile/Profile.tsx
=> chore: adjust checkpoints for 2024 edition

layout/Attendee/Store/Store.tsx
=> chore: add stock warning to store

components/Social/index.jsx
=> feat: add discord server invite to socials

layout/ResetPassword/components/ResetPasswordForm/index.tsx
=> fix: button padding

layout/Sponsor/Visitors/Visitors.tsx
Adds a visitor counter to the top of the page (thanks @pedrofp4444 💙), adds SEI's mascot as a default profile picture. Removes odd pink outline from attendee profile pictures. Improves download all CVs button.
=> feat: improve visitors page

layout/Challenges/components/Challenges/Challenge/index.tsx, layout/FAQs/components/FindUs/index.tsx, layout/Sponsor/Visitors/Visitors.tsx, public/bean.html
All companies should now see the "Download All CVs" button even without having any visitors (this is to make sure that staff CVs are always available to companies)
=> fix: remove batch cv download button display condition

layout/FAQs/components/FindUs/index.tsx
=> feat: add link to phone number
